{"name": "test_incorrect[incorrect_data0]", "status": "passed", "attachments": [{"name": "log", "source": "f5e9ef0a-762c-4bbb-8dfa-d913d0149d0f-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "incorrect_data", "value": "{'username': '1303845892@qq.com', 'password': '', 'check': '密码不能为空'}"}], "start": 1594727143519, "stop": 1594727173193, "uuid": "d49f9e17-bb6e-4e07-bace-03de0989da47", "historyId": "e64c0af6fef26d85bcdee262d7a7479c", "testCaseId": "486418aa0944ed0ecb75b40c2b58e369", "fullName": "TestCases.test_login.TestLogin#test_incorrect", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-KFH4O7N"}, {"name": "thread", "value": "10824-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}