{"name": "test_incorrect[incorrect_data2]", "status": "passed", "attachments": [{"name": "log", "source": "8d9b282d-f013-418f-9df0-05cbc971b1c7-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "incorrect_data", "value": "{'username': '1303845892', 'password': 'nmb_python', 'check': '用户不存在'}"}], "start": 1594727891014, "stop": 1594727936969, "uuid": "3876d2fa-af53-4cb5-9181-17434d188e99", "historyId": "9a23aa568774cb1eb1113c9dc5db5449", "testCaseId": "486418aa0944ed0ecb75b40c2b58e369", "fullName": "TestCases.test_login.TestLogin#test_incorrect", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-KFH4O7N"}, {"name": "thread", "value": "25668-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}