{"name": "test_incorrect[incorrect_data0]", "status": "passed", "attachments": [{"name": "log", "source": "1c9573d1-83a6-4bc9-a4ec-8869eba675bd-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "incorrect_data", "value": "{'username': '1303845892@qq.com', 'password': '', 'check': '密码不能为空'}"}], "start": 1594725604713, "stop": 1594725638461, "uuid": "7f45ccc8-0040-4469-856f-6fc5bb9ab132", "historyId": "e64c0af6fef26d85bcdee262d7a7479c", "testCaseId": "486418aa0944ed0ecb75b40c2b58e369", "fullName": "TestCases.test_login.TestLogin#test_incorrect", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-KFH4O7N"}, {"name": "thread", "value": "12400-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}